In [1]:
numbers = [1254,
1313,
1456,
1782,
1742,
1391,
1273,
1286,
1373,
1891,
1188,
1994,
1887,
1816,
1984,
961,
1428,
1105,
1123,
1699,
1154,
1953,
1977,
1450,
1696,
1068,
1241,
1926,
1228,
1591,
1789,
1966,
1508,
1193,
1190,
1654,
444,
1282,
1169,
1165,
1778,
1669,
1570,
1671,
1845,
1208,
1728,
1798,
847,
1300,
1817,
1200,
1297,
1658,
1296,
1571,
1991,
1305,
1314,
1903,
1472,
1359,
1506,
1999,
1877,
1168,
1137,
1288,
1083,
1656,
413,
1430,
1408,
1397,
1846,
1218,
684,
1234,
2007,
900,
1604,
1460,
1848,
1693,
1324,
1401,
1968,
1918,
1975,
1665,
1413,
1874,
1852,
1521,
1753,
1229,
1940,
1650,
1976,
1235,
1130,
1927,
1365,
1908,
1441,
1302,
1986,
1449,
1692,
1944,
1277,
1312,
1826,
1231,
1289,
1814,
1170,
1606,
1608,
1773,
1883,
1936,
1626,
1497,
1860,
1673,
1295,
2005,
1481,
1995,
1734,
1646,
1557,
1298,
1174,
1894,
1309,
1240,
1982,
1414,
1799,
1620,
1863,
1220,
1642,
508,
1146,
1187,
1253,
1284,
1952,
1527,
1610,
1333,
1221,
1362,
1457,
1721,
1493,
1330,
156,
1647,
1841,
1724,
2000,
1398,
1745,
1985,
1269,
1722,
2001,
1923,
1395,
1094,
1140,
1958,
1239,
1336,
1588,
1338,
1750,
1757,
1444,
1822,
1335,
1941,
1865,
1767,
1881,
1499,
1157,
1990,
1210,
1779,
1201,
1784,
1961,
1476,
1861,
1468]

In [2]:
for a in numbers:
    for b in numbers:
        if a + b == 2020:
            print(a, b, a * b)

684 1336 913824
1336 684 913824

In [3]:
from itertools import combinations

pairs = combinations(numbers,2)

for pair in pairs:
    if sum(pair) == 2020:
        print(pair[0], pair[1], pair[0] * pair[1])

684 1336 913824

In [4]:
for a in numbers:
    for b in numbers:
        for c in numbers:
            if a + b + c == 2020:
                print(a, b, c, a * b * c)

1068 444 508 240889536
1068 508 444 240889536
444 1068 508 240889536
444 508 1068 240889536
508 1068 444 240889536
508 444 1068 240889536

In [10]:
pairs = combinations(numbers,3)
import numpy as np

for pair in pairs:
    if sum(pair) == 2020:
        print(np.prod(pair))

240889536

In [13]:
import numpy as np
np.sort(numbers)

array([ 156,  413,  444,  508,  684,  847,  900,  961, 1068, 1083, 1094,
       1105, 1123, 1130, 1137, 1140, 1146, 1154, 1157, 1165, 1168, 1169,
       1170, 1174, 1187, 1188, 1190, 1193, 1200, 1201, 1208, 1210, 1218,
       1220, 1221, 1228, 1229, 1231, 1234, 1235, 1239, 1240, 1241, 1253,
       1254, 1269, 1273, 1277, 1282, 1284, 1286, 1288, 1289, 1295, 1296,
       1297, 1298, 1300, 1302, 1305, 1309, 1312, 1313, 1314, 1324, 1330,
       1333, 1335, 1336, 1338, 1359, 1362, 1365, 1373, 1391, 1395, 1397,
       1398, 1401, 1408, 1413, 1414, 1428, 1430, 1441, 1444, 1449, 1450,
       1456, 1457, 1460, 1468, 1472, 1476, 1481, 1493, 1497, 1499, 1506,
       1508, 1521, 1527, 1557, 1570, 1571, 1588, 1591, 1604, 1606, 1608,
       1610, 1620, 1626, 1642, 1646, 1647, 1650, 1654, 1656, 1658, 1665,
       1669, 1671, 1673, 1692, 1693, 1696, 1699, 1721, 1722, 1724, 1728,
       1734, 1742, 1745, 1750, 1753, 1757, 1767, 1773, 1778, 1779, 1782,
       1784, 1789, 1798, 1799, 1814, 1816, 1817, 1822, 1826, 1841, 1845,
       1846, 1848, 1852, 1860, 1861, 1863, 1865, 1874, 1877, 1881, 1883,
       1887, 1891, 1894, 1903, 1908, 1918, 1923, 1926, 1927, 1936, 1940,
       1941, 1944, 1952, 1953, 1958, 1961, 1966, 1968, 1975, 1976, 1977,
       1982, 1984, 1985, 1986, 1990, 1991, 1994, 1995, 1999, 2000, 2001,
       2005, 2007])

In [14]:
# In case of two numbers, only these have to be checked with the rest:
for n in numbers:
    if n < 1010:
        print(n)
        
# Also, only two even or two uneven are necessary

961
444
847
413
684
900
508
156